### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by zach-betz-hln** [emmercm/www#244]
Hi @emmercm - just wanted to drop a note saying thank you for your blog.

My colleague and I were having a friendly debate on whether [tini](https://github.com/krallin/tini) was required, and at first, I argued that it was, at least in order for Node.js to pass along signals...

Then my colleague linked me your articles:

- https://emmer.dev/blog/you-don-t-need-an-init-system-for-node.js-in-docker/
- https://emmer.dev/blog/docker-shell-vs.-exec-form/

After reading them, and some local experimentation, I stand corrected, and am now handling shutdown signals gracefully in our Express.js server. (And the code is much more explicit about what is actually happening). 

So, thanks for putting this info out there 🙂 Cheers.

**Comment by emmercm** [comment]
Thank you @zach-betz-hln , this was high praise and a delight to read!

I haven't written an Express app in a while now but I'm glad I can pay it forward. I was using [dumb-init](https://github.com/Yelp/dumb-init) and might still recommend something like it as a default in the future, but mostly as a failsafe.

Cheers to you!
